-- Add missing fields to Dealer table
ALTER TABLE "Dealer"
ADD COLUMN IF NOT EXISTS "legalName" TEXT,
ADD COLUMN IF NOT EXISTS "email" TEXT,
ADD COLUMN IF NOT EXISTS "addressLine2" TEXT,
ADD COLUMN IF NOT EXISTS "postalCode" TEXT,
ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'US',
ADD COLUMN IF NOT EXISTS "active" BOOLEAN DEFAULT true;
