-- Update UserRole enum to include AFFILIATE_ONLY and DEALER_USER
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'AFFILIATE_ONLY';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'DEALER_USER';

-- Add new fields to User table
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "first_name" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "last_name" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "is_affiliate" BOOLEAN DEFAULT false;
